name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'

    - name: Install dependencies
      run: |
        gem install cocoapods
        pod install

    - name: Build
      run: xcodebuild -workspace project.xcworkspace -scheme YourApp -sdk iphoneos -configuration Release archive -archivePath ${{ github.workspace }}/build/YourApp.xcarchive

    - name: Export IPA
      run: xcodebuild -exportArchive -archivePath ${{ github.workspace }}/build/YourApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ${{ github.workspace }}/build

    - name: Upload IPA and APP
      uses: actions/upload-artifact@v3
      with:
        name: app-artifacts
        path: |
          ${{ github.workspace }}/build/*.ipa
          ${{ github.workspace }}/build/*.app
